import { IElementConfig } from '../../interfaces';

/**
 * https://www.home-assistant.io/integrations/philips_js/
 */
export const philipsTVDefaultKeys: IElementConfig[] = [
	{
		type: 'button',
		name: 'power',
		tap_action: { action: 'key', key: 'KEY_POWER' },
		icon: 'mdi:power',
	},
	{
		type: 'button',
		name: 'power_on',
		tap_action: { action: 'key', key: 'PowerOn' },
		icon: 'mdi:power-on',
	},
	{
		type: 'button',
		name: 'power_off',
		tap_action: { action: 'key', key: 'PowerOff' },
		icon: 'mdi:power-off',
	},
	{
		type: 'button',
		name: 'home',
		tap_action: { action: 'key', key: 'Home' },
		icon: 'mdi:home',
	},
	{
		type: 'button',
		name: 'back',
		tap_action: { action: 'key', key: 'Back' },
		icon: 'mdi:keyboard-backspace',
	},
	{
		type: 'button',
		name: 'menu',
		tap_action: { action: 'key', key: 'PhilipsMenu' },
		icon: 'mdi:menu',
	},
	{
		type: 'button',
		name: 'options',
		tap_action: { action: 'key', key: 'Options' },
		icon: 'mdi:backburger',
	},
	{
		type: 'button',
		name: 'volume_up',
		tap_action: { action: 'key', key: 'VolumeUp' },
		hold_action: { action: 'repeat' },
		icon: 'mdi:volume-high',
	},
	{
		type: 'button',
		name: 'volume_down',
		tap_action: { action: 'key', key: 'VolumeDown' },
		hold_action: { action: 'repeat' },
		icon: 'mdi:volume-medium',
	},
	{
		type: 'button',
		name: 'volume_mute',
		tap_action: { action: 'key', key: 'Mute' },
		icon: 'mdi:volume-low',
	},
	{
		type: 'button',
		name: 'volume_buttons',
		icon: 'mdi:volume-plus',
	},
	{
		type: 'slider',
		name: 'slider',
		range: [0, 1],
		step: 0.01,
		value_attribute: 'volume_level',
		tap_action: {
			action: 'perform-action',
			perform_action: 'media_player.volume_set',
			data: {
				volume_level: '{{ value | float }}',
			},
		},
	},
	{
		type: 'button',
		name: 'up',
		tap_action: { action: 'key', key: 'CursorUp' },
		hold_action: { action: 'repeat' },
		icon: 'mdi:chevron-up',
	},
	{
		type: 'button',
		name: 'down',
		tap_action: { action: 'key', key: 'CursorDown' },
		hold_action: { action: 'repeat' },
		icon: 'mdi:chevron-down',
	},
	{
		type: 'button',
		name: 'left',
		tap_action: { action: 'key', key: 'CursorLeft' },
		hold_action: { action: 'repeat' },
		icon: 'mdi:chevron-left',
	},
	{
		type: 'button',
		name: 'right',
		tap_action: { action: 'key', key: 'CursorRight' },
		hold_action: { action: 'repeat' },
		icon: 'mdi:chevron-right',
	},
	{
		type: 'button',
		name: 'center',
		tap_action: { action: 'key', key: 'Confirm' },
		icon: 'mdi:circle',
	},
	{
		type: 'button',
		name: 'navigation_buttons',
		icon: 'mdi:gamepad',
	},
	{
		type: 'button',
		name: 'dpad',
		icon: 'mdi:gamepad',
	},
	{
		type: 'touchpad',
		name: 'touchpad',
		tap_action: {
			action: 'key',
			key: 'Confirm',
		},
		up: {
			tap_action: { action: 'key', key: 'CursorUp' },
			hold_action: { action: 'repeat' },
		},
		down: {
			tap_action: { action: 'key', key: 'CursorDown' },
			hold_action: { action: 'repeat' },
		},
		left: {
			tap_action: { action: 'key', key: 'CursorLeft' },
			hold_action: { action: 'repeat' },
		},
		right: {
			tap_action: { action: 'key', key: 'CursorRight' },
			hold_action: { action: 'repeat' },
		},
	},
	{
		type: 'touchpad',
		name: 'dragpad',
		tap_action: {
			action: 'key',
			key: 'Confirm',
		},
		drag_action: {
			action: 'key',
			key: 'Cursor{{ ("Right" if deltaX > 0 else "Left") if (deltaX | abs) > (deltaY | abs) else ("Down" if deltaY > 0 else "Up") }}',
			repeat_delay: 100,
		},
		multi_drag_action: {
			action: 'key',
			key: 'Cursor{{ ("Right" if deltaX > 0 else "Left") if (deltaX | abs) > (deltaY | abs) else ("Down" if deltaY > 0 else "Up") }}',
			repeat_delay: 50,
		},
		up: {},
		down: {},
		left: {},
		right: {},
		icon: 'mdi:drag-variant',
	},
	{
		type: 'button',
		name: 'play_pause',
		tap_action: {
			action: 'perform-action',
			perform_action: 'media_player.media_play_pause',
		},
		icon: 'mdi:play-pause',
	},
	{
		type: 'button',
		name: 'play',
		tap_action: { action: 'key', key: 'Play' },
		icon: 'mdi:play',
	},
	{
		type: 'button',
		name: 'pause',
		tap_action: { action: 'key', key: 'Pause' },
		icon: 'mdi:pause',
	},
	{
		type: 'button',
		name: 'rewind',
		tap_action: { action: 'key', key: 'Rewind' },
		icon: 'mdi:rewind',
	},
	{
		type: 'button',
		name: 'fast_forward',
		tap_action: { action: 'key', key: 'FastForward' },
		icon: 'mdi:fast-forward',
	},
	{
		type: 'button',
		name: 'stop',
		tap_action: { action: 'key', key: 'Stop' },
		icon: 'mdi:stop',
	},
	{
		type: 'button',
		name: 'record',
		tap_action: { action: 'key', key: 'Record' },
		icon: 'mdi:record',
	},
	{
		type: 'button',
		name: 'channel_up',
		tap_action: { action: 'key', key: 'ChannelStepUp' },
		icon: 'mdi:arrow-up-circle',
	},
	{
		type: 'button',
		name: 'channel_down',
		tap_action: { action: 'key', key: 'ChannelStepDown' },
		icon: 'mdi:arrow-down-circle',
	},
	{
		type: 'button',
		name: 'red',
		tap_action: { action: 'key', key: 'RedColour' },
		icon: 'mdi:alpha-r-box',
	},
	{
		type: 'button',
		name: 'green',
		tap_action: { action: 'key', key: 'GreenColour' },
		icon: 'mdi:alpha-g-box',
	},
	{
		type: 'button',
		name: 'yellow',
		tap_action: { action: 'key', key: 'YellowColour' },
		icon: 'mdi:alpha-y-box',
	},
	{
		type: 'button',
		name: 'blue',
		tap_action: { action: 'key', key: 'BlueColour' },
		icon: 'mdi:alpha-b-box',
	},
	{
		type: 'button',
		name: 'n0',
		tap_action: { action: 'key', key: 'Digit0' },
		icon: 'mdi:numeric-0',
	},
	{
		type: 'button',
		name: 'n1',
		tap_action: { action: 'key', key: 'Digit1' },
		icon: 'mdi:numeric-1',
	},
	{
		type: 'button',
		name: 'n2',
		tap_action: { action: 'key', key: 'Digit2' },
		icon: 'mdi:numeric-2',
	},
	{
		type: 'button',
		name: 'n3',
		tap_action: { action: 'key', key: 'Digit3' },
		icon: 'mdi:numeric-3',
	},
	{
		type: 'button',
		name: 'n4',
		tap_action: { action: 'key', key: 'Digit4' },
		icon: 'mdi:numeric-4',
	},
	{
		type: 'button',
		name: 'n5',
		tap_action: { action: 'key', key: 'Digit5' },
		icon: 'mdi:numeric-5',
	},
	{
		type: 'button',
		name: 'n6',
		tap_action: { action: 'key', key: 'Digit6' },
		icon: 'mdi:numeric-6',
	},
	{
		type: 'button',
		name: 'n7',
		tap_action: { action: 'key', key: 'Digit7' },
		icon: 'mdi:numeric-7',
	},
	{
		type: 'button',
		name: 'n8',
		tap_action: { action: 'key', key: 'Digit8' },
		icon: 'mdi:numeric-8',
	},
	{
		type: 'button',
		name: 'n9',
		tap_action: { action: 'key', key: 'Digit9' },
		icon: 'mdi:numeric-9',
	},
	{
		type: 'button',
		name: 'numpad',
		icon: 'mdi:dialpad',
	},
	{
		type: 'button',
		name: 'info',
		tap_action: { action: 'key', key: 'Info' },
		icon: 'mdi:information',
	},
	{
		type: 'button',
		name: 'guide',
		tap_action: { action: 'key', key: 'TvGuide' },
		icon: 'mdi:television-box',
	},
	{
		type: 'button',
		name: 'captions',
		tap_action: { action: 'key', key: 'ClosedCaption' },
		icon: 'mdi:closed-caption',
	},
	{
		type: 'button',
		name: 'tools',
		tap_action: { action: 'key', key: 'Options' },
		icon: 'mdi:hammer-screwdriver',
	},
	{
		type: 'button',
		name: 'smart_tv',
		tap_action: { action: 'key', key: 'SmartTV' },
		icon: 'mdi:television',
	},
	{
		type: 'button',
		name: 'source',
		tap_action: { action: 'key', key: 'Source' },
		icon: 'mdi:import',
	},
	{
		type: 'button',
		name: 'tv',
		tap_action: { action: 'key', key: 'WatchTV' },
		icon: 'mdi:television',
	},
	{
		type: 'button',
		name: 'ambient',
		tap_action: { action: 'key', key: 'AmbilightOnOff' },
		icon: 'mdi:television-ambient-light',
	},
	{
		type: 'button',
		name: 'tv',
		tap_action: { action: 'key', key: 'WatchTV' },
		icon: 'mdi:television',
	}
];
